### ISSUE TITLE
Duplicate key value violates unique constraint "sessions_name__key"

### ISSUE THREAD

**Issue by 1Map** [express-rate-limit/rate-limit-postgresql#18]
### Description

Randomly I get an error message like:

```
error: duplicate key value violates unique constraint "sessions_name__key"
    at c:\myapp\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (C:\myapp\lib\internal\process\task_queues.js:95:5)
    at async createNewSession (c:\myapp\node_modules\@acpr\rate-limit-postgresql\dist\index.mjs:53:18)
    at async PostgresStoreAggregatedIP.increment (c:\myapp\node_modules\@acpr\rate-limit-postgresql\dist\index.mjs:304:22)
    at async file:///C:/myapp/node_modules/express-rate-limit/dist/index.mjs:602:40
    at async file:///C:/myapp/node_modules/express-rate-limit/dist/index.mjs:583:5 {length: 263, name: 'error', severity: 'ERROR', code: '23505', detail: 'Key (name_)=(aggregated_store) already exists.', …}
```

My Rate Limiter is setup as:

```
import { rateLimit } from 'express-rate-limit'
import { PostgresStore } from '@acpr/rate-limit-postgresql'

const apiRateLimiter = rateLimit({
  store: new PostgresStore(
    {
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      host: process.env.DB_HOST,
      database: process.env.DB_DATABASE,
      port: parseInt(process.env.DB_PORT)
    },
    'aggregated_store'
  ),
  windowMs: 1 * 60 * 1000, // 1 minute
  limit: 600, // limit each IP/email to 600 requests per windowMs (1 minute) - 10 requests per second
  delayMs: 0, // disable delaying - user has full speed until the max limit is reached
  standardHeaders: 'draft-7', // draft-6: `RateLimit-*` headers; draft-7: combined `RateLimit` header
  legacyHeaders: false, // Disable the `X-RateLimit-*` headers.
  keyGenerator: (req, res) => {
    if (req?.currentUser?.email) {
      return req.currentUser.email
    } else {
      return req.ip
    }
  }
})
```

### Library version

^1.3.2

### Node version

20.11.0

### Module system

ESM

**Comment by nfriedly** [comment]
Closing this one in favor of #17
